# Generated by Django 5.2.3 on 2025-06-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('description', models.TextField(verbose_name='توضیحات و مشخصات فنی')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='کد یا مدل محصول')),
                ('brand', models.CharField(max_length=100, verbose_name='برند')),
                ('category', models.CharField(max_length=100, verbose_name='دسته\u200cبندی')),
                ('stock_status', models.CharField(choices=[('AVAILABLE', 'موجود در انبار'), ('OUT_OF_STOCK', 'ناموجود'), ('COMING_SOON', 'به زودی')], default='AVAILABLE', max_length=20, verbose_name='وضعیت موجودی')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='تصویر اصلی محصول')),
            ],
        ),
    ]
