# Generated by Django 5.2.3 on 2025-06-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True, verbose_name='مشخصات محصول (هر خط یک مشخصه)'),
        ),
    ]
