# Generated by Django 5.2.3 on 2025-07-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_price_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_caption',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='توضیح زیر تصویر'),
        ),
    ]
