# Generated by Django 5.2.3 on 2025-07-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='piece_count',
            field=models.PositiveIntegerField(default=1, verbose_name='تعداد قطعات'),
        ),
    ]
