# Generated by Django 5.2.3 on 2025-07-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_piece_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='piece_count',
        ),
    ]
